title: ARKONIS
description: Kubernetes-native AI agent infrastructure
url: https://arkonis.dev

remote_theme: just-the-docs/just-the-docs@v0.10.0

permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

color_scheme: dark

mermaid:
  version: "10"

aux_links:
  GitHub: https://github.com/arkonis-dev/arkonis-operator

footer_content: "Apache 2.0 · ARKONIS"

exclude:
  - README.md
